<a href="https://colab.research.google.com/github/Calebchike/Supermarket-Pulse/blob/Using-Python-Panda-Series/Supermarket_Pulse_Using_Panda_Series.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Import Libraries**

In [1]:
import numpy as np
import pandas as pd

# **Load the CSV data**
Load Raw dataset, determine the rows and columns and convert columns to Panda series

In [16]:
supermarket_raw = pd.read_csv("https://raw.githubusercontent.com/Calebchike/Supermarket-Pulse/refs/heads/main/SuperMarket%20Analysis.csv", index_col="Invoice ID") #import supermarket csv file as a dataframe
supermarket_raw.head()                                         #prints the dataframe

,Branch,City_CustType,Gender,Product line,Unit price,Quantity,Tax 5%,Sales,Date,Time,Payment,cogs,gross margin percentage,gross income,Rating
Invoice ID,,,,,,,,,,,,,,,
750-67-8428,Alex,Yangon|Member,Female,Health and beauty,74.69,7,26.1415,548.9715,01/05/2019,1:08:00 pm,Ewallet,522.83,4.761905,26.1415,9.1
226-31-3081,Giza,Naypyitaw|Normal,Female,Electronic accessories,15.28,5,3.8200,80.2200,03/08/2019,10:29:00 am,Cash,76.40,4.761905,3.8200,9.6
631-41-3108,Alex,Yangon|Normal,Female,Home and lifestyle,46.33,7,16.2155,340.5255,03/03/2019,1:23:00 pm,Credit card,324.31,4.761905,16.2155,7.4
123-19-1176,Alex,Yangon|Member,Female,Health and beauty,58.22,8,23.2880,489.0480,1/27/2019,8:33:00 pm,Ewallet,465.76,4.761905,23.2880,NaN
373-73-7910,Alex,Yangon|Member,Female,Sports and travel,86.31,7,30.2085,634.3785,02/08/2019,10:37:00 am,Ewallet,604.17,4.761905,30.2085,5.3

### Get the Number of Rows and Columns contained in the dataset

In [5]:
supermarket_raw.shape     #get the number of rows and column in the data

(1000, 15)

### Get all the column Headers in a List for referencing

In [17]:
supermarket_raw.columns.to_list()                         #prints all the heading of the dataframe as a list

['Branch',
 'City_CustType',
 'Gender',
 'Product line',
 'Unit price',
 'Quantity',
 'Tax 5%',
 'Sales',
 'Date',
 'Time',
 'Payment',
 'cogs',
 'gross margin percentage',
 'gross income',
 'Rating']

This cell creates Panda series for the Columns

In [19]:
branch = pd.Series(supermarket_raw["Branch"], index = supermarket_raw.index, name="Branch")
city_custtype = pd.Series(supermarket_raw["City_CustType"], index=supermarket_raw.index, name="City_CustType")
gender = pd.Series(supermarket_raw["Gender"], index=supermarket_raw.index, name="Gender")
product_line = pd.Series(supermarket_raw["Product line"], index=supermarket_raw.index, name="Product line")
unit_price = pd.Series(supermarket_raw["Unit price"], index=supermarket_raw.index, name="Unit price")
quantity = pd.Series(supermarket_raw["Quantity"], index=supermarket_raw.index, name="Quantity")
tax = pd.Series(supermarket_raw["Tax 5%"], index=supermarket_raw.index, name="Tax")
sales = pd.Series(supermarket_raw["Sales"], index=supermarket_raw.index, name="Sales")
date = pd.Series(supermarket_raw["Date"], index=supermarket_raw.index, name="Date")
time = pd.Series(supermarket_raw["Time"], index=supermarket_raw.index, name="Time")
payment = pd.Series(supermarket_raw["Payment"], index=supermarket_raw.index, name="Payment")
cogs = pd.Series(supermarket_raw["cogs"], index=supermarket_raw.index, name="cogs")
gross_margin_percentage = pd.Series(supermarket_raw["gross margin percentage"], index=supermarket_raw.index, name="gross margin percentage")
gross_income = pd.Series(supermarket_raw["gross income"], index=supermarket_raw.index, name="gross income")
rating = pd.Series(supermarket_raw["Rating"], index=supermarket_raw.index, name="Rating")

# **Data Cleaning**

## Split Column
This cell Split "City_CustType" column into two separate columns using the |
delimiter. and Named them "City" and "Customer Type".

In [26]:
city = city_custtype.str.split("|").str[0]
customer_type = city_custtype.str.split("|").str[1]
city.name = "City"
customer_type.name = "Customer Type"
display(city.head())
display(customer_type.head())

Invoice ID
750-67-8428       Yangon
226-31-3081    Naypyitaw
631-41-3108       Yangon
123-19-1176       Yangon
373-73-7910       Yangon
Name: City, dtype: object

Invoice ID
750-67-8428    Member
226-31-3081    Normal
631-41-3108    Normal
123-19-1176    Member
373-73-7910    Member
Name: Customer Type, dtype: object

## Standardize Text
The Product line column has inconsistent capitalization. Force a l text in
this column to "Capitalize Each Word".

## Calculate sales of each customer