<a href="https://colab.research.google.com/github/Calebchike/Supermarket-Pulse/blob/Using-Python-Panda-Series/Supermarket_Pulse_Using_Panda_Series.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Import Libraries**

In [100]:
# Import necessary libraries: numpy for numerical operations and pandas for data manipulation.
import numpy as np
import pandas as pd

# **Load the CSV data**
Load Raw dataset, determine the rows and columns and convert columns to Panda series

In [101]:
# Load the supermarket sales data from a CSV file into a pandas DataFrame.
# The 'Invoice ID' column is set as the index.
# The .head() method is used to display the first few rows of the DataFrame.
supermarket_raw = pd.read_csv("https://raw.githubusercontent.com/Calebchike/Supermarket-Pulse/refs/heads/main/SuperMarket%20Analysis.csv", index_col="Invoice ID") #import supermarket csv file as a dataframe
supermarket_raw.head()                                         #prints the dataframe

,Branch,City_CustType,Gender,Product line,Unit price,Quantity,Tax 5%,Sales,Date,Time,Payment,cogs,gross margin percentage,gross income,Rating
Invoice ID,,,,,,,,,,,,,,,
750-67-8428,Alex,Yangon|Member,Female,Health and beauty,74.69,7,26.1415,548.9715,01/05/2019,1:08:00 pm,Ewallet,522.83,4.761905,26.1415,9.1
226-31-3081,Giza,Naypyitaw|Normal,Female,Electronic accessories,15.28,5,3.8200,80.2200,03/08/2019,10:29:00 am,Cash,76.40,4.761905,3.8200,9.6
631-41-3108,Alex,Yangon|Normal,Female,Home and lifestyle,46.33,7,16.2155,340.5255,03/03/2019,1:23:00 pm,Credit card,324.31,4.761905,16.2155,7.4
123-19-1176,Alex,Yangon|Member,Female,Health and beauty,58.22,8,23.2880,489.0480,1/27/2019,8:33:00 pm,Ewallet,465.76,4.761905,23.2880,NaN
373-73-7910,Alex,Yangon|Member,Female,Sports and travel,86.31,7,30.2085,634.3785,02/08/2019,10:37:00 am,Ewallet,604.17,4.761905,30.2085,5.3

### Get the Number of Rows and Columns contained in the dataset

In [102]:
# Display the number of rows and columns in the DataFrame using the .shape attribute.
supermarket_raw.shape     #get the number of rows and column in the data

(1000, 15)

### Get all the column Headers in a List for referencing

In [103]:
# Get a list of all column headers (names) from the DataFrame.
supermarket_raw.columns.to_list()                         #prints all the heading of the dataframe as a list

['Branch',
 'City_CustType',
 'Gender',
 'Product line',
 'Unit price',
 'Quantity',
 'Tax 5%',
 'Sales',
 'Date',
 'Time',
 'Payment',
 'cogs',
 'gross margin percentage',
 'gross income',
 'Rating']

This cell creates Panda series for the Columns

In [104]:
# Create individual pandas Series for each column in the raw supermarket data.
# Each Series is indexed by 'Invoice ID' and named after its respective column.
branch = pd.Series(supermarket_raw["Branch"], index = supermarket_raw.index, name="Branch")
city_custtype = pd.Series(supermarket_raw["City_CustType"], index=supermarket_raw.index, name="City_CustType")
gender = pd.Series(supermarket_raw["Gender"], index=supermarket_raw.index, name="Gender")
product_line = pd.Series(supermarket_raw["Product line"], index=supermarket_raw.index, name="Product line")
unit_price = pd.Series(supermarket_raw["Unit price"], index=supermarket_raw.index, name="Unit price")
quantity = pd.Series(supermarket_raw["Quantity"], index=supermarket_raw.index, name="Quantity")
tax = pd.Series(supermarket_raw["Tax 5%"], index=supermarket_raw.index, name="Tax")
sales = pd.Series(supermarket_raw["Sales"], index=supermarket_raw.index, name="Sales")
date = pd.Series(supermarket_raw["Date"], index=supermarket_raw.index, name="Date")
time = pd.Series(supermarket_raw["Time"], index=supermarket_raw.index, name="Time")
payment = pd.Series(supermarket_raw["Payment"], index=supermarket_raw.index, name="Payment")
cogs = pd.Series(supermarket_raw["cogs"], index=supermarket_raw.index, name="cogs")
gross_margin_percentage = pd.Series(supermarket_raw["gross margin percentage"], index=supermarket_raw.index, name="gross margin percentage")
gross_income = pd.Series(supermarket_raw["gross income"], index=supermarket_raw.index, name="gross income")
rating = pd.Series(supermarket_raw["Rating"], index=supermarket_raw.index, name="Rating")

# **Data Cleaning**

## Split Column
This cell Split "City_CustType" column into two separate columns using the |
delimiter. and Named them "City" and "Customer Type".

In [105]:
# Split the 'City_CustType' Series into two new Series: 'City' and 'Customer Type',
# using the '|' delimiter. Then display the first few entries of each new Series.
city = city_custtype.str.split("|").str[0]
customer_type = city_custtype.str.split("|").str[1]
city.name = "City"
customer_type.name = "Customer Type"
display(city.head())
display(customer_type.head())

Invoice ID
750-67-8428       Yangon
226-31-3081    Naypyitaw
631-41-3108       Yangon
123-19-1176       Yangon
373-73-7910       Yangon
Name: City, dtype: object

Invoice ID
750-67-8428    Member
226-31-3081    Normal
631-41-3108    Normal
123-19-1176    Member
373-73-7910    Member
Name: Customer Type, dtype: object

## Standardize Text
The Product line column has inconsistent capitalization. This cells Forces all text in the column to "Capitalize Each Word".

In [106]:
# Display the first few entries of the 'product_line' Series to show its current capitalization.
product_line.head()

Invoice ID
750-67-8428         Health and beauty
226-31-3081    Electronic accessories
631-41-3108        Home and lifestyle
123-19-1176         Health and beauty
373-73-7910         Sports and travel
Name: Product line, dtype: object

In [107]:
# Standardize the 'product_line' Series by stripping any leading/trailing whitespace
# and then capitalizing the first letter of each word in the strings.
# Finally, display the first few entries of the standardized Series.
product_line = product_line.str.strip().str.title()
product_line.head()

Invoice ID
750-67-8428         Health And Beauty
226-31-3081    Electronic Accessories
631-41-3108        Home And Lifestyle
123-19-1176         Health And Beauty
373-73-7910         Sports And Travel
Name: Product line, dtype: object

## Handling Nulls
 This cell Filters out all transactions where the customer Rating was left blank.

In [108]:
# Display the first few entries of the 'rating' Series and its total size.
rating.head()
rating.size

1000

In [109]:
# Identify and store the indices of transactions where 'rating' is null.
# Then, drop these null-rating transactions from all relevant Series to maintain data consistency.
# Finally, display the first few entries and the new size of the 'rating' Series.
null_rating = [x for x in rating.index if pd.isnull(rating[x])]

branch = branch.drop(null_rating)
city = city.drop(null_rating)
customer_type = customer_type.drop(null_rating)
gender = gender.drop(null_rating)
product_line = product_line.drop(null_rating)
unit_price = unit_price.drop(null_rating)
quantity = quantity.drop(null_rating)
tax = tax.drop(null_rating)
sales = sales.drop(null_rating)
date = date.drop(null_rating)
time = time.drop(null_rating)
payment = payment.drop(null_rating)
cogs = cogs.drop(null_rating)
gross_margin_percentage = gross_margin_percentage.drop(null_rating)
gross_income = gross_income.drop(null_rating)
rating = rating.drop(null_rating)

rating.head()
rating.size

974

## Data Types
Ensure Unit price, Quantity and Sales are properly formatted as float, integer and float respectively.

In [110]:
# Print the data types of the 'unit_price', 'quantity', and 'sales' Series
# to verify they are in the expected float and integer formats.
print(f"Unit Price data type: {unit_price.dtype}")
print(f"Quantity data type: {quantity.dtype}")
print(f"Sales data type: {sales.dtype}")

Unit Price data type: float64
Quantity data type: int64
Sales data type: float64

# **Baseline Metrics & Margin of Error**

## Measures of Central Tendency:
Calculate the Mean, Median, and Mode for the Sales transaction
value.

In [111]:
# Calculate and print the Mean, Median, and Mode of the 'sales' Series.
# The mode might return multiple values, so it's converted to a list for display.
print(f"The Mean of the Total Sales is: {sales.mean()}")
print(f"The Median of the Total Sales is: {sales.median()}")
print(f"The Mode of the Total Sales are: {sales.mode().to_list()}")

The Mean of the Total Sales is: 322.2604265913758
The Median of the Total Sales is: 253.386
The Mode of the Total Sales are: [87.234, 93.744, 175.917, 189.0945, 216.846, 217.6335, 263.97, 276.948, 470.988, 829.08]

## Measures of Dispersion:
Calculate the sample Variance and sample Standard Deviation for the customer Rating column.

In [112]:
# Calculate and print the sample Variance and Standard Deviation of the 'rating' Series,
# formatted to 4 significant figures.
print(f"The Variance of the Rating is: {rating.var():.4g}")
print(f"The Standard Deviation of the Rating is: {rating.std():.4g}")

The Variance of the Rating is: 2.964
The Standard Deviation of the Rating is: 1.722

## Margin of Error:
Take a random sample of 60 transactions. Calculate the Standard Error and Margin of Error for the Total sales value, assuming a 95% confidence level (Z-score = 1.96).

In [113]:
# Take a random sample of 60 transactions from the 'sales' Series.
# Calculate and print the Mean, Standard Error (sem), and Margin of Error (assuming a 95% confidence level with Z-score = 1.96)
# for this random sample, formatted to 4 decimal places.
random_sixty = sales.sample(60)
print(f"The Mean of the Random Sample is: {random_sixty.mean():.4f}")
print(f"The Standard Error of the Random Sample is: {random_sixty.sem():.4f}")
print(f"The Margin of Error of the Random Sample is: {1.96 * random_sixty.sem():.4f}")

The Mean of the Random Sample is: 329.9433
The Standard Error of the Random Sample is: 30.3811
The Margin of Error of the Random Sample is: 59.5469

# **Probability Distributions**

## Import Modules:
Import `norm` and `binom` modules from `scipy.stats` for Normal and Binomial distribution calculations, respectively.

In [114]:
from scipy.stats import norm
from scipy.stats import binom

## The Normal Distribution (Sales Revenue)

What is the probability that the next customer's total bill will be $500 or less?

In [115]:
# 1. Calculate the mean and standard deviation from the Sales column.
mean_sales = sales.mean()
std_sales = sales.std()

probability_500 = norm.cdf(500, loc=mean_sales, scale=std_sales)

print(f"There is a {probability_500 * 100:.2f}% chance the next bill will be $500 or less.")

There is a 76.53% chance the next bill will be $500 or less.

What is the probability that a customer's bill will be greater than $800?

In [116]:
probability_800 = norm.cdf(800, loc=mean_sales, scale=std_sales)
print(f"There is a {100 - (probability_800 * 100):.2f}% chance the next bill will be greater than $800.")

There is a 2.59% chance the next bill will be greater than $800.

## Binomial Distribution(Payment Methods)

Find probability of success for "Credit card" transactions. If 50 customers walk into the store in the next hour, what is the
exact probability that exactly 20 of them will pay with a Credit card?

In [117]:
# Baseline probability of all payment method
payment_probabilities = payment.value_counts(normalize=True)
payment_probabilities.name = "Probability"
display(payment_probabilities)

p_success_credit_card = payment_probabilities['Credit card']
n_trials = 50     # Total customers walking in
k_successes = 20  # Exact number of credit card users wanted

exact_probability = binom.pmf(k_successes, n = n_trials, p = p_success_credit_card)

print()
print(f"Probability that exactly 20 out of 50 customers will pay with a Credit Card: {exact_probability * 100:.2f}%")

Payment
Ewallet        0.348049
Cash           0.344969
Credit card    0.306982
Name: Probability, dtype: float64

Probability that exactly 20 out of 50 customers will pay with a Credit Card: 4.34%

What is the probability that exactly 0 out of the next 10 customers use a Credit
card?

In [118]:
n_trials = 10     # Total customers walking in
k_successes = 0   # Exact number of credit card users wanted

exact_probability = binom.pmf(k_successes, n = n_trials, p = p_success_credit_card)

print(f"Probability that exactly 0 out of 10 customers will pay with a Credit Card: {exact_probability * 100:.2f}%")

Probability that exactly 0 out of 10 customers will pay with a Credit Card: 2.56%